sudo: required
services:
  - docker
before_install:
  - docker build -t chranveer/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true chranveer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-562377326721"
  bucket_path: "docker-react"
  on:
    branch: master
